name: bsky_kmb_bot
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

dependencies:
  bluesky: ^0.15.7
  bluesky_text: ^0.6.8
  cron: ^0.6.0
  fullwidth_halfwidth_converter: ^1.0.2
  http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
